#!/bin/sh

agendafile="$HOME/.agenda"

checkDate()
{
	weekday=$1   day=$2   month=$3   year=$4
	format1="$weekday"   format2="$day$month"   format3="$day$month$year"

	IFS="|"
	echo "On the agenda for today:"

	while read date description ; do
		if [ "$date" = "$format1" -o "$date" = "$format2" -o \
			"$date" = "$format3" ]
		then
			echo "  $description"
		fi
	done < $agendafile
}

if [ ! -e $agendafile ] ; then
  echo "$0: You don't seem to have an .agenda file. " >&2
  echo "To remedy this, please use 'addagenda' to add events" >&2
  exit 1
fi

eval $(date '+weekday="%a" month="%b" day="%e" year="%G"')

day="$(echo $day|sed 's/ //g')"

checkDate $weekday $day $month $year

exit 0
