#!/bin/bash

# 공식은 1융자 금액, 2이자율, 3융자 기간(연)을 입력받으면 회당 상환액 계산한다.

# M = P * ( J / (1 - (1 + J) ^ -N)),
# P = 원금, J = 월마다의 이자율, N = 기간(개월 수)
. ../library.sh

if [ $# -ne 3 ] ; then
	echo "Usage: $0 principal interest loan-duration-years" >&2
	exit 1
fi

P=$1 I=$2 L=$3
J="$(scriptbc -p 8 $I / \( 12 \* 100 \) )"
N="$(( $L * 12 ))"
M="$(scriptbc -p 8 $P \* \( $J / \(1 - \(1 + $J\) \^ -$N\) \) )"

dollars="$(echo $M | cut -d. -f1)"
cents="$(echo $M | cut -d. -f2 | cut -c-2)"

cat << EOF
A $L-year Loan at $I% interest with a principal amount of $(nicenumber $P 1 ) results in a payment of \$$dollars. $cents each month for duration of the loan ($N payments).
EOF

exit 0
