#!/bin/bash

sftpacct="takeoutmoenywallet@naver.com"
tarballname="AllFiles.tgz"
localsource="$HOME/scripts/web"
remotedir="~/scripts"
timestamp=".timestamp"
count=0


if [ ! -d "$localsource" ] ; then
	echo "$0: Error: directory $localsource doesn't exist?" >&2
	exit 1
fi

cd "$localsource"

if [ ! -f $timestamp ] ; then
	for filename in *
	do 
		if [ -f "$filename" ] ; then
			count=$(( $count + 1 ))
		fi
		done
else
	count=$(find . -newer $timestamp -type f -print | wc -l)
fi

if [ $count -eq 0 ] ; then
	echo "$(basename $0): No files found in $localsource to sync with remote."
	exit 0
fi

echo "Making tarball archive file for upload"

tar -czf $tarballname ./*

exec sftpsync $sftpacct $remotedir
